const progressBar=document.getElementById('progressBar');
window.addEventListener('scroll',()=>{const h=document.documentElement;const p=h.scrollTop/(h.scrollHeight-h.clientHeight)*100;if(progressBar)progressBar.style.width=p+'%';},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const modal=document.getElementById('modal'),close=document.getElementById('modalClose'),kicker=document.getElementById('modalKicker'),title=document.getElementById('modalTitle'),body=document.getElementById('modalBody');
const cases={
 ahmed:{kicker:'AHMED AL MAGHRIBI PERFUMES · BAHRAIN',title:'E-commerce Operations & Performance',body:'<p>Day-to-day e-commerce operations across the Bahrain website and marketplace channels, including Talabat, Jahez and Sharaf DG.</p><p>The work covers product catalog and listing management, pricing and promotions, availability, campaign coordination, order and cancellation monitoring, reporting and performance analysis.</p><p><strong>Analytics:</strong> Excel / reporting dashboards and Looker Studio analysis snapshots.</p>'},
 visusoft:{kicker:'VISUSOFT · HYDERABAD',title:'Performance Dashboard & Reporting Automation',body:'<p>A structured tracker bringing ads and affiliate data into a repeatable reporting workflow.</p><p>The portfolio preview shows total ads spend, ads sales, commission, affiliate sales, ACOS, weekly comparisons, growth views and ads-versus-affiliate analysis.</p><p>The underlying workbook is not published here.</p>'}
};
document.querySelectorAll('[data-open]').forEach(btn=>btn.addEventListener('click',()=>{const c=cases[btn.dataset.open];if(!c)return;kicker.textContent=c.kicker;title.textContent=c.title;body.innerHTML=c.body;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
close.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
